import os

os.environ['SERVER_MAC'] = 'YOUR_MAC_ADDRESS'
os.environ['SERVER_IP'] = 'YOUR_LOCAL_SERVER_IP'
os.environ['SERVER_PORT'] = 'YOUR_LOCAL_SERVER_PORT'
os.environ['SERVER_SSH_LOGIN'] = 'USERNAME@YOUR_LOCAL_SERVER_IP'
os.environ['PUBLIC_SERVER_IP'] = 'YOUR_PUBLIC_SERVER_IP'
os.environ['PUBLIC_SERVER_PORT'] = 'YOUR_PUBLIC_SERVER_PORT'
os.environ['OFICIAL_BOT_KEY'] = 'YOUR_OFFICIAL_BOT_KEY'
os.environ['TEST_BOT_KEY'] = 'YOUR_TEST_BOT_KEY'
