name: cig-pope

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: cig-pope-image
      run: sudo docker build . --file Dockerfile --tag cig-pope && sudo docker run --publish 8000:5000 cig-pope
