name: cig-pope

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: cig-pope-image
      run: docker-compose -f docker-compose.yaml up -d
